site_name: AIC313/CS378 Introduction to Generative Models (KAIST, Fall 2026)
site_url: https://diffusion.kaist.ac.kr/
site_author: Minhyuk Sung

theme:
  name: material
  icon:
    logo: material/cube-outline
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - footnotes
  - meta
  - tables
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - macros

copyright: Copyright &copy; 2026 Minhyuk Sung

nav:
  - Home: index.md

extra:
  analytics:
    provider: google
    property: G-1VHYJZSMF1
  links:
    lec01: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0lRQ3E1dzFMQk9ZdlJyUm9oaGU3eHFrZUFid1ozUllIbFBIel9EQVQyT0cwZmN3P2U9OURzS0o5&cid=60562023B6640282&id=60562023B6640282%21s4b0de7aae604462fb4688617bbc6a91e&parId=60562023B6640282%21s6facf5ce255248ab8e3a6a4eb357ee90&o=OneUp
    lec02: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0lRRENQanpxbzlweVJybWhJVk4yMlN3NEFTWnBqLXNHcE1hNkZxWExkZFNUZmpjP2U9UGw1dzdX&cid=60562023B6640282&id=60562023B6640282%21sea3c3ec2daa34672b9a1215376d92c38&parId=60562023B6640282%21s6facf5ce255248ab8e3a6a4eb357ee90&o=OneUp
    rec02: https://youtu.be/96XoVM7PYtQ
    zoom: https://kaist.zoom.us/j/85365206376
